name: Lint

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  Lint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4.1.5

      - name: Cache Plugin Directory
        uses: actions/cache@v4.0.2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: v0.51.1

      - name: Intialize TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact
